const GET_API_RECIPES = 'GET_API_RECIPES'
const GET_DB_RECIPES = 'GET_DB_RECIPES'
const GET_RECIPES_BY_NAME = 'GET_RECIPES_BY_NAME'
const GET_DIETS = 'GET_DIETS'
const CHANGE_PAGE = 'CHANGE_PAGE'
const CREATE_RECIPE = 'CREATE_RECIPE'
const SEARCH_RECIPE = 'SEARCH_RECIPE'
const ORDER = 'ORDER'
const FILTER = 'FILTER'

module.exports = {
    GET_API_RECIPES,
    GET_DB_RECIPES,
    GET_RECIPES_BY_NAME,
    GET_DIETS,
    CHANGE_PAGE,
    CREATE_RECIPE,
    SEARCH_RECIPE,
    ORDER,
    FILTER
}

